PHTRS_DEMO/config/routes.rb
Rails.application.routes.draw do
  resources :workorders
  resources :potholes

end

PHTRS_DEMO/app/models/pothole.rb
class Pothole < ActiveRecord::Base
  has_one :workorder
  validates_inclusion_of :size, :in => 1..10, :message =>"should be between 1 and 10"
end

PHTRS_DEMO/app/models/workorder.rb
class Workorder < ActiveRecord::Base
  belongs_to :pothole
end

PHTRS_DEMO/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

PHTRS_DEMO/app/controllers/potholes_controller.rb
class PotholesController < ApplicationController
  before_action :set_pothole, only: [:show, :edit, :update, :destroy]

  # GET /potholes
  # GET /potholes.json
  def index
    @potholes = Pothole.all
  end

  # GET /potholes/1
  # GET /potholes/1.json
  def show
  end

  # GET /potholes/new
  def new
    @pothole = Pothole.new
  end

  # GET /potholes/1/edit
  def edit
  end

  # POST /potholes
  # POST /potholes.json
  def create
    @pothole = Pothole.new(pothole_params)

    respond_to do |format|
      if @pothole.save
        format.html { redirect_to @pothole, notice: 'Pothole was successfully created.' }
        format.json { render :show, status: :created, location: @pothole }
      else
        format.html { render :new }
        format.json { render json: @pothole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /potholes/1
  # PATCH/PUT /potholes/1.json
  def update
    respond_to do |format|
      if @pothole.update(pothole_params)
        format.html { redirect_to @pothole, notice: 'Pothole was successfully updated.' }
        format.json { render :show, status: :ok, location: @pothole }
      else
        format.html { render :edit }
        format.json { render json: @pothole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /potholes/1
  # DELETE /potholes/1.json
  def destroy
    @pothole.destroy
    respond_to do |format|
      format.html { redirect_to potholes_url, notice: 'Pothole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pothole
      @pothole = Pothole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pothole_params
      params.require(:pothole).permit(:name, :district, :address, :location, :size)
    end
end

PHTRS_DEMO/app/controllers/workorders_controller.rb
class WorkordersController < ApplicationController
  before_action :set_workorder, only: [:show, :edit, :update, :destroy]

  # GET /workorders
  # GET /workorders.json
  def index
    @workorders = Workorder.all
  end

  # GET /workorders/1
  # GET /workorders/1.json
  def show
  end

  # GET /workorders/new
  def new
    @workorder = Workorder.new
  end

  # GET /workorders/1/edit
  def edit
  end

  # POST /workorders
  # POST /workorders.json
  def create
    @workorder = Workorder.new(workorder_params)

    respond_to do |format|
      if @workorder.save
        format.html { redirect_to @workorder, notice: 'Workorder was successfully created.' }
        format.json { render :show, status: :created, location: @workorder }
      else
        format.html { render :new }
        format.json { render json: @workorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workorders/1
  # PATCH/PUT /workorders/1.json
  def update
    respond_to do |format|
      if @workorder.update(workorder_params)
        format.html { redirect_to @workorder, notice: 'Workorder was successfully updated.' }
        format.json { render :show, status: :ok, location: @workorder }
      else
        format.html { render :edit }
        format.json { render json: @workorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workorders/1
  # DELETE /workorders/1.json
  def destroy
    @workorder.destroy
    respond_to do |format|
      format.html { redirect_to workorders_url, notice: 'Workorder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workorder
      @workorder = Workorder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workorder_params
      params.require(:workorder).permit(:PID, :crewnum, :assigned_equipment, :hours)
    end
end

PHTRS_DEMO/app/helpers/application_helper.rb
module ApplicationHelper
end

PHTRS_DEMO/app/helpers/potholes_helper.rb
module PotholesHelper
end

PHTRS_DEMO/app/helpers/workorders_helper.rb
module WorkordersHelper
end

PHTRS_DEMO/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PHTRSDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

PHTRS_DEMO/app/views/potholes/_form.html.erb
<%= form_for(@pothole) do |f| %>
  <% if @pothole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pothole.errors.count, "error") %> prohibited this pothole from being saved:</h2>

      <ul>
      <% @pothole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PHTRS_DEMO/app/views/potholes/edit.html.erb
<h1>Editing Pothole</h1>

<%= render 'form' %>

<%= link_to 'Show', @pothole %> |
<%= link_to 'Back', potholes_path %>

PHTRS_DEMO/app/views/potholes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Potholes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>District</th>
      <th>Address</th>
      <th>Location</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @potholes.each do |pothole| %>
      <tr>
        <td><%= pothole.name %></td>
        <td><%= pothole.district %></td>
        <td><%= pothole.address %></td>
        <td><%= pothole.location %></td>
        <td><%= pothole.size %></td>
        <td><%= link_to 'Show', pothole %></td>
        <td><%= link_to 'Edit', edit_pothole_path(pothole) %></td>
        <td><%= link_to 'Destroy', pothole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pothole', new_pothole_path %>

PHTRS_DEMO/app/views/potholes/new.html.erb
<h1>New Pothole</h1>

<%= render 'form' %>

<%= link_to 'Back', potholes_path %>

PHTRS_DEMO/app/views/potholes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pothole.name %>
</p>

<p>
  <strong>District:</strong>
  <%= @pothole.district %>
</p>

<p>
  <strong>Address:</strong>
  <%= @pothole.address %>
</p>

<p>
  <strong>Location:</strong>
  <%= @pothole.location %>
</p>

<p>
  <strong>Size:</strong>
  <%= @pothole.size %>
</p>

<%= link_to 'Edit', edit_pothole_path(@pothole) %> |
<%= link_to 'Back', potholes_path %>

PHTRS_DEMO/app/views/workorders/_form.html.erb
<%= form_for(@workorder) do |f| %>
  <% if @workorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workorder.errors.count, "error") %> prohibited this workorder from being saved:</h2>

      <ul>
      <% @workorder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PID %><br>
    <%= f.number_field :PID %>
  </div>
  <div class="field">
    <%= f.label :crewnum %><br>
    <%= f.number_field :crewnum %>
  </div>
  <div class="field">
    <%= f.label :assigned_equipment %><br>
    <%= f.text_field :assigned_equipment %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.number_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PHTRS_DEMO/app/views/workorders/edit.html.erb
<h1>Editing Workorder</h1>

<%= render 'form' %>

<%= link_to 'Show', @workorder %> |
<%= link_to 'Back', workorders_path %>

PHTRS_DEMO/app/views/workorders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workorders</h1>

<table>
  <thead>
    <tr>
      <th>Pid</th>
      <th>Crewnum</th>
      <th>Assigned equipment</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workorders.each do |workorder| %>
      <tr>
        <td><%= workorder.PID %></td>
        <td><%= workorder.crewnum %></td>
        <td><%= workorder.assigned_equipment %></td>
        <td><%= workorder.hours %></td>
        <td><%= link_to 'Show', workorder %></td>
        <td><%= link_to 'Edit', edit_workorder_path(workorder) %></td>
        <td><%= link_to 'Destroy', workorder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workorder', new_workorder_path %>|
<%= link_to 'Back', potholes_path  %>

PHTRS_DEMO/app/views/workorders/new.html.erb
<h1>New Workorder</h1>

<%= render 'form' %>

<%= link_to 'Back', workorders_path %>

PHTRS_DEMO/app/views/workorders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pid:</strong>
  <%= @workorder.PID %>
</p>

<p>
  <strong>Crewnum:</strong>
  <%= @workorder.crewnum %>
</p>

<p>
  <strong>Assigned equipment:</strong>
  <%= @workorder.assigned_equipment %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @workorder.hours %>
</p>

<%= link_to 'Edit', edit_workorder_path(@workorder) %> |
<%= link_to 'Back', workorders_path %>